export interface Room {
  title: string;
  titleService?: string;
  images: string[];
  services: string[];
}

const roomsDataEs: Room[] = [
  {
    title: "HABITACION CLASICA",
    images: [
      "Clasica-mat-1.webp",
      "Clasica-bano-1.webp",
      "clasica-doble-1.webp",
    ],
    services: [],
  },
  {
    title: "HABITACION PREMIUM",
    titleService: "SERVICIOS ADICIONALES",
    images: [
      "premium-matrimonial-1.webp",
      "Premium-Triple-1.webp",
      "Premium-familiar-1.webp",
      "Premium-familiar-bano1-1.webp",
      "Premium-bano-1.webp",
      "Ameneties-premium.webp",
      "Premium-triple1.webp",
      "Premium-twin.webp",
    ],
    services: [
      "Espejo de aumento para maquillarse o afeitarse",
      "Baños remodelados con porcelanato italiano de piso a techo",
      "Batas",
      "Pantuflas",
      "Toalla de Algodón",
      "Selección de Amenities de baño mejorada",
      "Teléfono en el baño",
      "Ubicación preferencial",
      "Habitaciones conectadas (con solicitud previa)",
      'LED de 50" Smart TV',
      "Traslados aeropuerto-hotel o viceversa de cortesía",
      "Minibar",
      'Colchas de pluma de ganso blanco "Pacific Coast"',
      "Botella de agua de bienvenida",
      "Habitaciones más amplias",
      "Kit de infusiones",
    ],
  },
  {
    title: "HABITACION JUNIOR SUITE",
    titleService: "SERVICIOS ADICIONALES",
    images: [
      "Ameneties-premium.webp",
      "Junior-Suite2.webp",
      "Junior-Suite1.webp",
      "Junior-Suite-bano1.webp",
      "Junior-Suite-bano2.webp",
    ],
    services: [
      "Espejo de aumento para maquillarse o afeitarse",
      "Baños remodelados con porcelanato italiano de piso a techo",
      "Batas",
      "Pantuflas",
      "Toalla de Algodón",
      "Selección de Amenities de baño mejorada",
      "Teléfono en el baño",
      "Ubicación preferencial",
      "Habitaciones conectadas (con solicitud previa)",
      'LED de 50" Smart TV',
      "Traslados aeropuerto-hotel o viceversa de cortesía",
      "Minibar",
      'Colchas de pluma de ganso blanco "Pacific Coast"',
      "Botella de agua de bienvenida",
      "Habitaciones más amplias",
      "Kit de infusiones",
    ],
  },
  {
    title: "SUITE",
    titleService: "SERVICIOS ADICIONALES",
    images: [
      "Ameneties-premium.webp",
      "Suite10.webp",
      "Suite-1-1.webp",
      "Suite2.webp",
      "Suite3.webp",
      "suite4.webp",
      "suite5.webp",
      "Suite7.webp",
      "Suite9.webp",
    ],
    services: [
      "Espejo de aumento para maquillarse o afeitarse",
      "Baños remodelados con porcelanato italiano de piso a techo",
      "Batas",
      "Pantuflas",
      "Toalla de Algodón",
      "Selección de Amenities de baño mejorada",
      "Teléfono en el baño",
      "Ubicación preferencial",
      "Habitaciones conectadas (con solicitud previa)",
      'LED de 50" Smart TV',
      "Traslados aeropuerto-hotel o viceversa de cortesía",
      "Minibar",
      'Colchas de pluma de ganso blanco "Pacific Coast"',
      "Botella de agua de bienvenida",
      "Habitaciones más amplias",
      "Kit de infusiones",
    ],
  },
];

const roomsDataEn: Room[] = [
  {
    title: "CLASSIC ROOM",
    images: [
      "Clasica-mat-1.webp",
      "Clasica-bano-1.webp",
      "clasica-doble-1.webp",
    ],
    services: [],
  },
  {
    title: "PREMIUM ROOM",
    titleService: "ADDITIONAL SERVICES",
    images: [
      "premium-matrimonial-1.webp",
      "Premium-Triple-1.webp",
      "Premium-familiar-1.webp",
      "Premium-familiar-bano1-1.webp",
      "Premium-bano-1.webp",
      "Ameneties-premium.webp",
      "Premium-triple1.webp",
      "Premium-twin.webp",
    ],
    services: [
      "Magnifying mirror for makeup or shaving",
      "Remodeled bathrooms with Italian porcelain from floor to ceiling",
      "Bathrobes",
      "Slippers",
      "Cotton Towels",
      "Enhanced bathroom amenities selection",
      "Telephone in the bathroom",
      "Preferential location",
      "Connecting rooms (upon prior request)",
      '50" Smart LED TV',
      "Complimentary airport-hotel transfers",
      "Minibar",
      '"Pacific Coast" white goose down comforters',
      "Welcome water bottle",
      "Larger rooms",
      "Infusion kit",
    ],
  },
  {
    title: "JUNIOR SUITE ROOM",
    titleService: "ADDITIONAL SERVICES",
    images: [
      "Ameneties-premium.webp",
      "Junior-Suite2.webp",
      "Junior-Suite1.webp",
      "Junior-Suite-bano1.webp",
      "Junior-Suite-bano2.webp",
    ],
    services: [
      "Magnifying mirror for makeup or shaving",
      "Remodeled bathrooms with Italian porcelain from floor to ceiling",
      "Bathrobes",
      "Slippers",
      "Cotton Towels",
      "Enhanced bathroom amenities selection",
      "Telephone in the bathroom",
      "Preferential location",
      "Connecting rooms (upon prior request)",
      '50" Smart LED TV',
      "Complimentary airport-hotel transfers",
      "Minibar",
      '"Pacific Coast" white goose down comforters',
      "Welcome water bottle",
      "Larger rooms",
      "Infusion kit",
    ],
  },
  {
    title: "SUITE",
    titleService: "ADDITIONAL SERVICES",
    images: [
      "Ameneties-premium.webp",
      "Suite10.webp",
      "Suite-1-1.webp",
      "Suite2.webp",
      "Suite3.webp",
      "suite4.webp",
      "suite5.webp",
      "Suite7.webp",
      "Suite9.webp",
    ],
    services: [
      "Magnifying mirror for makeup or shaving",
      "Remodeled bathrooms with Italian porcelain from floor to ceiling",
      "Bathrobes",
      "Slippers",
      "Cotton Towels",
      "Enhanced bathroom amenities selection",
      "Telephone in the bathroom",
      "Preferential location",
      "Connecting rooms (upon prior request)",
      '50" Smart LED TV',
      "Complimentary airport-hotel transfers",
      "Minibar",
      '"Pacific Coast" white goose down comforters',
      "Welcome water bottle",
      "Larger rooms",
      "Infusion kit",
    ],
  },
];

export function getRoomsData(locale = 'es') {
  return locale === 'en' ? roomsDataEn : roomsDataEs;
}