export const roomsData = [
  {
    title: "HABITACION CLASICA",
    images: [
      "/images/rooms/Clasica-mat-1.webp",
      "/images/rooms/Clasica-bano-1.webp",
      "/images/rooms/clasica-doble-1.webp",
    ],
    services: [
    ],
  },
  {
    title: "HABITACION PREMIUM",
    titleService: "SERVICIOS ADICIONALES",
    images: [
      "/images/rooms/premium-matrimonial-1.webp",
      "/images/rooms/Premium-Triple-1.webp",
      "/images/rooms/Premium-familiar-1.webp",
      "/images/rooms/Premium-familiar-bano1-1.webp",
      "/images/rooms/Premium-bano-1.webp",
      "/images/rooms/Ameneties-premium.webp",
      "/images/rooms/Premium-triple1.webp",
      "/images/rooms/Premium-twin.webp",
    ],
    services: [
      "Espejo de aumento para maquillarse o afeitarse",
      'LBaños remodelados con porcelanato italiano de piso a techo',
      "Batas",
      "Pantuflas",
      'Toalla de Algodon',
      "Selección de Amenities de baño mejorada",
      "Teléfono en el baño",
      "Ubicación preferencial",

      "Habitaciones conectadas (con solicitud previa)",
      'LED de 50" Smart TV',
      "Traslados aeropuerto-hotel o viceversa de cortesía",
      "Minibar",
      'Colchas de pluma de ganso blanco "Pacific Coast"',
      "Botella de agua de bienvenida",
      "Habitaciones más amplias",
      "Kit de infusiones",
    ],
  },
  {
    title: "HABITACION JUNIOR SUITE",
    titleService: "SERVICIOS ADICIONALES",

    images: [
      "/images/rooms/Ameneties-premium.webp",
      "/images/rooms/Junior-Suite2.webp",
      "/images/rooms/Junior-Suite1.webp",
      "/images/rooms/Junior-Suite-bano1.webp",
      "/images/rooms/Junior-Suite-bano2.webp",
    ],
    services: [
      "Espejo de aumento para maquillarse o afeitarse",
      'LBaños remodelados con porcelanato italiano de piso a techo',
      "Batas",
      "Pantuflas",
      'Toalla de Algodon',
      "Selección de Amenities de baño mejorada",
      "Teléfono en el baño",
      "Ubicación preferencial",

      "Habitaciones conectadas (con solicitud previa)",
      'LED de 50" Smart TV',
      "Traslados aeropuerto-hotel o viceversa de cortesía",
      "Minibar",
      'Colchas de pluma de ganso blanco "Pacific Coast"',
      "Botella de agua de bienvenida",
      "Habitaciones más amplias",
      "Kit de infusiones",
    ],
  },
  {
    title: "SUITE",
    titleService: "SERVICIOS ADICIONALES",

    images: [
      "/images/rooms/Ameneties-premium.webp",
      "/images/rooms/Suite10.webp",
      "/images/rooms/Suite-1-1.webp",
      "/images/rooms/Suite2.webp",
      "/images/rooms/Suite3.webp",
      "/images/rooms/suite4.webp",
      "/images/rooms/suite5.webp",
      "/images/rooms/Suite7.webp",
      "/images/rooms/Suite9.webp",
    ],
   services: [
      "Espejo de aumento para maquillarse o afeitarse",
      'LBaños remodelados con porcelanato italiano de piso a techo',
      "Batas",
      "Pantuflas",
      'Toalla de Algodon',
      "Selección de Amenities de baño mejorada",
      "Teléfono en el baño",
      "Ubicación preferencial",

      "Habitaciones conectadas (con solicitud previa)",
      'LED de 50" Smart TV',
      "Traslados aeropuerto-hotel o viceversa de cortesía",
      "Minibar",
      'Colchas de pluma de ganso blanco "Pacific Coast"',
      "Botella de agua de bienvenida",
      "Habitaciones más amplias",
      "Kit de infusiones",
    ],
  },
];
